services:
  playtome:
    build:
      context: .
      dockerfile: Playtome/Dockerfile
    image: ${DOCKER_REGISTRY-}playtome
    container_name: Playtome
    restart: unless-stopped
    volumes:
      - ./Playtome:/var/www/html
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: playtome
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_CONNECTION: mysql
    depends_on:
      - mysql-db
    ports:
      - 8001:80
    command: >
      sh -c "sleep 10 && php artisan migrate --force && apache2-foreground"

  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  mysql_data:
